ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1( )

      IMPLICIT NONE

      INCLUDE 'model_functions.inc'
      INCLUDE '../vector.inc'


      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_1 = -(MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_2 = (2.000000D+00*MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_3 = -(MDL_EE*MDL_COMPLEXI)
      GC_4 = MDL_EE*MDL_COMPLEXI
      GC_52 = (MDL_EE*MDL_COMPLEXI)/(MDL_SW*MDL_SQRT__2)
      GC_62 = -(MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_SW)
      GC_63 = (MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_SW)
      GC_64 = (MDL_CW*MDL_EE*MDL_COMPLEXI)/MDL_SW
      GC_68 = -(MDL_EE*MDL_COMPLEXI*MDL_SW)/(6.000000D+00*MDL_CW)
      GC_69 = (MDL_EE*MDL_COMPLEXI*MDL_SW)/(2.000000D+00*MDL_CW)
      GC_73 = (MDL_EE__EXP__2*MDL_COMPLEXI*MDL_VEV)/(2.000000D+00
     $ *MDL_SW__EXP__2)
      GC_75 = -((MDL_COMPLEXI*MDL_YB)/MDL_SQRT__2)
      GC_76 = -((MDL_COMPLEXI*MDL_YC)/MDL_SQRT__2)
      GC_77 = -((MDL_COMPLEXI*MDL_YDO)/MDL_SQRT__2)
      GC_78 = -((MDL_COMPLEXI*MDL_YE)/MDL_SQRT__2)
      GC_80 = -((MDL_COMPLEXI*MDL_YS)/MDL_SQRT__2)
      GC_83 = -((MDL_COMPLEXI*MDL_YUP)/MDL_SQRT__2)
      GC_84 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM1X1)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_85 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM1X2)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_86 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM1X3)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_87 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM2X1)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_88 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM2X2)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_89 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM2X3)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_90 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM3X1)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_91 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM3X2)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_92 = (MDL_EE*MDL_COMPLEXI*MDL_CONJG__CKM3X3)/(MDL_SW
     $ *MDL_SQRT__2)
      GC_10 = -(MDL_IMETALCT/MDL_SQRT__2)-(MDL_COMPLEXI*MDL_REETALCT)
     $ /MDL_SQRT__2
      GC_12 = -(MDL_IMETALUT/MDL_SQRT__2)-(MDL_COMPLEXI*MDL_REETALUT)
     $ /MDL_SQRT__2
      GC_14 = -(MDL_IMETARCT/MDL_SQRT__2)-(MDL_COMPLEXI*MDL_REETARCT)
     $ /MDL_SQRT__2
      GC_16 = -(MDL_IMETARUT/MDL_SQRT__2)-(MDL_COMPLEXI*MDL_REETARUT)
     $ /MDL_SQRT__2
      END
