ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cabi = ', MDL_CABI
      WRITE(*,*) 'mdl_MD = ', MDL_MD
      WRITE(*,*) 'mdl_MU = ', MDL_MU
      WRITE(*,*) 'mdl_MS = ', MDL_MS
      WRITE(*,*) 'mdl_MC = ', MDL_MC
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_Me = ', MDL_ME
      WRITE(*,*) 'mdl_MMU = ', MDL_MMU
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_ReXLut = ', MDL_REXLUT
      WRITE(*,*) 'mdl_ImXLut = ', MDL_IMXLUT
      WRITE(*,*) 'mdl_ReXRut = ', MDL_REXRUT
      WRITE(*,*) 'mdl_ImXRut = ', MDL_IMXRUT
      WRITE(*,*) 'mdl_ReXLct = ', MDL_REXLCT
      WRITE(*,*) 'mdl_ImXLct = ', MDL_IMXLCT
      WRITE(*,*) 'mdl_ReXRct = ', MDL_REXRCT
      WRITE(*,*) 'mdl_ImXRct = ', MDL_IMXRCT
      WRITE(*,*) 'mdl_ReKLut = ', MDL_REKLUT
      WRITE(*,*) 'mdl_ImKLut = ', MDL_IMKLUT
      WRITE(*,*) 'mdl_ReKRut = ', MDL_REKRUT
      WRITE(*,*) 'mdl_ImKRut = ', MDL_IMKRUT
      WRITE(*,*) 'mdl_ReKLct = ', MDL_REKLCT
      WRITE(*,*) 'mdl_ImKLct = ', MDL_IMKLCT
      WRITE(*,*) 'mdl_ReKRct = ', MDL_REKRCT
      WRITE(*,*) 'mdl_ImKRct = ', MDL_IMKRCT
      WRITE(*,*) 'mdl_ReZetaLut = ', MDL_REZETALUT
      WRITE(*,*) 'mdl_ImZetaLut = ', MDL_IMZETALUT
      WRITE(*,*) 'mdl_ReZetaRut = ', MDL_REZETARUT
      WRITE(*,*) 'mdl_ImZetaRut = ', MDL_IMZETARUT
      WRITE(*,*) 'mdl_ReZetaLct = ', MDL_REZETALCT
      WRITE(*,*) 'mdl_ImZetaLct = ', MDL_IMZETALCT
      WRITE(*,*) 'mdl_ReZetaRct = ', MDL_REZETARCT
      WRITE(*,*) 'mdl_ImZetaRct = ', MDL_IMZETARCT
      WRITE(*,*) 'mdl_ReEtaLut = ', MDL_REETALUT
      WRITE(*,*) 'mdl_ImEtaLut = ', MDL_IMETALUT
      WRITE(*,*) 'mdl_ReEtaRut = ', MDL_REETARUT
      WRITE(*,*) 'mdl_ImEtaRut = ', MDL_IMETARUT
      WRITE(*,*) 'mdl_ReEtaLct = ', MDL_REETALCT
      WRITE(*,*) 'mdl_ImEtaLct = ', MDL_IMETALCT
      WRITE(*,*) 'mdl_ReEtaRct = ', MDL_REETARCT
      WRITE(*,*) 'mdl_ImEtaRct = ', MDL_IMETARCT
      WRITE(*,*) 'mdl_ReLambdaLut = ', MDL_RELAMBDALUT
      WRITE(*,*) 'mdl_ImLambdaLut = ', MDL_IMLAMBDALUT
      WRITE(*,*) 'mdl_ReLambdaRut = ', MDL_RELAMBDARUT
      WRITE(*,*) 'mdl_ImLambdaRut = ', MDL_IMLAMBDARUT
      WRITE(*,*) 'mdl_ReLambdaLct = ', MDL_RELAMBDALCT
      WRITE(*,*) 'mdl_ImLambdaLct = ', MDL_IMLAMBDALCT
      WRITE(*,*) 'mdl_ReLambdaRct = ', MDL_RELAMBDARCT
      WRITE(*,*) 'mdl_ImLambdaRct = ', MDL_IMLAMBDARCT
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymdo = ', MDL_YMDO
      WRITE(*,*) 'mdl_ymup = ', MDL_YMUP
      WRITE(*,*) 'mdl_yms = ', MDL_YMS
      WRITE(*,*) 'mdl_ymc = ', MDL_YMC
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_yme = ', MDL_YME
      WRITE(*,*) 'mdl_ymm = ', MDL_YMM
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cos__cabi = ', MDL_COS__CABI
      WRITE(*,*) 'mdl_CKM1x1 = ', MDL_CKM1X1
      WRITE(*,*) 'mdl_sin__cabi = ', MDL_SIN__CABI
      WRITE(*,*) 'mdl_CKM1x2 = ', MDL_CKM1X2
      WRITE(*,*) 'mdl_CKM1x3 = ', MDL_CKM1X3
      WRITE(*,*) 'mdl_CKM2x1 = ', MDL_CKM2X1
      WRITE(*,*) 'mdl_CKM2x2 = ', MDL_CKM2X2
      WRITE(*,*) 'mdl_CKM2x3 = ', MDL_CKM2X3
      WRITE(*,*) 'mdl_CKM3x1 = ', MDL_CKM3X1
      WRITE(*,*) 'mdl_CKM3x2 = ', MDL_CKM3X2
      WRITE(*,*) 'mdl_CKM3x3 = ', MDL_CKM3X3
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_conjg__CKM1x1 = ', MDL_CONJG__CKM1X1
      WRITE(*,*) 'mdl_conjg__CKM1x2 = ', MDL_CONJG__CKM1X2
      WRITE(*,*) 'mdl_conjg__CKM1x3 = ', MDL_CONJG__CKM1X3
      WRITE(*,*) 'mdl_conjg__CKM2x1 = ', MDL_CONJG__CKM2X1
      WRITE(*,*) 'mdl_conjg__CKM2x2 = ', MDL_CONJG__CKM2X2
      WRITE(*,*) 'mdl_conjg__CKM2x3 = ', MDL_CONJG__CKM2X3
      WRITE(*,*) 'mdl_conjg__CKM3x1 = ', MDL_CONJG__CKM3X1
      WRITE(*,*) 'mdl_conjg__CKM3x2 = ', MDL_CONJG__CKM3X2
      WRITE(*,*) 'mdl_conjg__CKM3x3 = ', MDL_CONJG__CKM3X3
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yc = ', MDL_YC
      WRITE(*,*) 'mdl_ydo = ', MDL_YDO
      WRITE(*,*) 'mdl_ye = ', MDL_YE
      WRITE(*,*) 'mdl_ym = ', MDL_YM
      WRITE(*,*) 'mdl_ys = ', MDL_YS
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_yup = ', MDL_YUP
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
