C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA TSTRATEGY(1)/2/
      DATA (IFOREST(I,-1,1),I=1,2)/6,5/
      DATA (SPROP(I,-1,1),I=1,1)/24/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/-1,4/
      DATA (SPROP(I,-2,1),I=1,1)/6/
      DATA TPRID(-2,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/1,-2/
      DATA TPRID(-3,1)/25/
      DATA (SPROP(I,-3,1),I=1,1)/0/
      DATA (IFOREST(I,-4,1),I=1,2)/-3,3/
      DATA TPRID(-4,1)/13/
      DATA (SPROP(I,-4,1),I=1,1)/0/
C     Number of configs
      DATA MAPCONFIG(0)/1/
C     used fake id
      DATA FAKE_ID/7/
