ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of topFCNC_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_52 = ', GC_52
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_63 = ', GC_63
      WRITE(*,2) 'GC_64 = ', GC_64
      WRITE(*,2) 'GC_68 = ', GC_68
      WRITE(*,2) 'GC_69 = ', GC_69
      WRITE(*,2) 'GC_73 = ', GC_73
      WRITE(*,2) 'GC_75 = ', GC_75
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_83 = ', GC_83
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_85 = ', GC_85
      WRITE(*,2) 'GC_86 = ', GC_86
      WRITE(*,2) 'GC_87 = ', GC_87
      WRITE(*,2) 'GC_88 = ', GC_88
      WRITE(*,2) 'GC_89 = ', GC_89
      WRITE(*,2) 'GC_90 = ', GC_90
      WRITE(*,2) 'GC_91 = ', GC_91
      WRITE(*,2) 'GC_92 = ', GC_92
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_16 = ', GC_16
