C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1)
C     
      SUBROUTINE FFS1P1N_2(F1, S3, COUP,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(6)
      COMPLEX*16 S3(*)
      F2(3)= COUP*(-CI )* F1(3)*S3(3)
      F2(4)= COUP*(-CI )* F1(4)*S3(3)
      F2(5)= COUP*0D0
      F2(6)= COUP*0D0
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1)
C     
      SUBROUTINE FFS1_2P1N_2(F1, S3, COUP1, COUP2,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(6)
      COMPLEX*16 FTMP(6)
      COMPLEX*16 S3(*)
      INTEGER*4 I
      CALL FFS1P1N_2(F1,S3,COUP1,F2)
      CALL FFS2P1N_2(F1,S3,COUP2,FTMP)
      DO I = 3, 6
        F2(I) = F2(I) + FTMP(I)
      ENDDO
      END


