ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of topFCNC_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_19 = ', GC_19
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_25 = ', GC_25
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_41 = ', GC_41
      WRITE(*,2) 'GC_43 = ', GC_43
      WRITE(*,2) 'GC_45 = ', GC_45
      WRITE(*,2) 'GC_47 = ', GC_47
      WRITE(*,2) 'GC_52 = ', GC_52
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_69 = ', GC_69
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_92 = ', GC_92
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_16 = ', GC_16
